/**:
  ros__parameters:
    use_sim_time: False
    serial_port: "/dev/serial/by-id/usb-T-frog_project_T-frog_Driver-if00"
    spur_params_file: "/home/tsukutsuku/tsukutsuku_ws/src/roboken/yp_robot_config/ypspur-robot-params/tsukutsuku.param"
    spur_args: "--admask 10000000 --enable-get-digital-io"
    frame_id: "odom"
    child_frame_id: "base_link"
    left_wheel_joint: "left_wheel_joint"
    right_wheel_joint: "right_wheel_joint"
    linear_vel_max: 2.0 #[m/s] 4[km/h] ~= 1.1[m/s]
    linear_acc_max: 1.0 #[m/s]
    angular_vel_max: 3.14 #[rad/s]
    angular_acc_max: 3.14 #[rad/s]
    pub_hz_: 50.0
