ypspur_ros_bridge:
  ros__parameters:
    use_sim_time: False
    frame_id: "odom"
    child_frame_id: "base_link"
    left_wheel: "left_wheel_joint"
    right_wheel: "right_wheel_joint"
    linear_vel_max: 2.0 #[m/s] 4[km/h] ~= 1.1[m/s]
    linear_acc_max: 4.0 #[m/s]
    angular_vel_max: 6.28 #[rad/s]
    angular_acc_max: 12.58 #[rad/s]
    pub_hz_: 25.0
